Improve documentation and examples
clue/reactphp-shell pull request #20
Opened 2024-01-30 10:20 UTC by yadaiio

This pull request builds on top of: https://github.com/clue/reactphp-sqlite/pull/43 and https://github.com/clue/reactphp-tar/pull/20.

2024-01-30 11:35 UTC, SimonFrings commented on README.md
> +php vendor/bin/phpunit
I think we use this version in other projects, should be apply the same here?

```suggestion
vendor/bin/phpunit
```

2024-02-01 07:25 UTC, yadaiio commented on README.md
> +php vendor/bin/phpunit
thank you for noticing this, should be fixed now.

2024-02-02 14:48 UTC, SimonFrings requested changes
Looks good so far, just noticed that `examples/php.php` could also need rejection handling, similar as you already did this in `examples/bash.php` & `examples/docker.php`

2024-02-06 07:43 UTC, yadaiio commented
oops, didn't saw the `then` in there 🤗 should also has a rejection handling now, thanks @SimonFrings

2024-02-06 08:56 UTC, SimonFrings approved these changes
Thanks for applying the requested changes, looks good to me :+1:

2024-02-07 17:22 UTC, clue approved these changes
@yadaiio Thanks for looking into this, changes LGTM! :shipit:

2024-02-07 17:22 UTC, merged